server:
  port: 9001
#&&allowPublicKeyRetrieval=True
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/housewifery?useSSL=false&&serverTimezone=UTC&&useUnicode=true&&characterEncoding=utf8
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml

#logging:
#  level:
#    com.yongsui: debug

# 私钥与公钥的存放地址
rsa:
  key:
    pubKeyFile: D://auth/id_key_rsa.pub
    priKeyFile: D://auth/id_key_rsa
